name: natta
favicon: null
layout_spectrum: 0.9647907793987542
typography_spectrum: 0.6953461808152497
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f9f9'
    - '#0d1e22'
    - '#a9acb6'
    - '#4c606c'
    - '#76828d'
  brandStrength: 0.125
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
